FROM jenkins/jenkins:lts
# Switch to root to install prerequisites
USER root

# Install Docker, Python3, and Pip
RUN apt-get update && \
    apt-get install -y docker.io python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment and place it in the PATH
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Checkov safely inside the venv
RUN pip install checkov

# Add jenkins user to docker group
RUN usermod -aG docker jenkins

# Revert to root user specifically for Docker socket communication
USER root
